# Generated by Django 4.0.4 on 2023-02-15 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcptUnit_team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VcptuTeam',
            new_name='VcptuTeamModal',
        ),
    ]
