# Generated by Django 4.1.7 on 2023-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcptUnit_team', '0002_rename_vcptuteam_vcptuteammodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcptuteammodal',
            name='unity_category',
            field=models.CharField(blank=True, choices=[('', 'Select Staff Tilte'), ('Core Management Team', 'Core Management Team'), ('Technicians', 'Technicians'), ('Data managers', 'Data managers'), ('Administrative officers', 'Administrative officers')], max_length=100, null=True),
        ),
    ]
