# Generated by Django 4.0.4 on 2023-02-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcptUnit_publication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VcptuPublications',
        ),
    ]
