# Generated by Django 4.0.4 on 2023-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcptUnit_publication', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcptupublications',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
