# Generated by Django 4.0.4 on 2023-02-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcptUnit_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcptunews',
            options={'verbose_name_plural': 'VCPTU-News'},
        ),
    ]
